import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import NextAuthProvider from "@/shared/providers/next-auth/Provider";
import { Provider } from "jotai";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Design Corner",
  description: "Generated by Design Corner",
  icons: [
    {
      url: "/logoDesign.svg",
      href: "/public/favicon.ico",
      rel: "logo",
    },
  ],
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Provider>
        <body  className={inter.className}>
          <NextAuthProvider>{children}</NextAuthProvider>
        </body>
      </Provider>
    </html>
  );
}
